const asyncStorageActionTypes = {
  GET_ITEM_REQUEST: 'GET_ITEM_REQUEST',
  GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
  GET_ITEM_FAILURE: 'GET_ITEM_FAILURE',

  SET_ITEM_REQUEST: 'SET_ITEM_REQUEST',
  SET_ITEM_SUCCESS: 'SET_ITEM_SUCCESS',
  SET_ITEM_FAILURE: 'SET_ITEM_FAILURE',
};

export { asyncStorageActionTypes as default };
