const authActionTypes = {
  //SYNC_USER_INFO: 'SYNC_USER_INFO',

  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  //BASIC_LOGIN_SUCCESS: 'BASIC_LOGIN_SUCCESS',
  FACEBOOK_LOGIN_SUCCESS: 'FACEBOOK_LOGIN_SUCCESS',
};

export { authActionTypes as default };
