const landingActionTypes = {
  SETUP_BANK_ACCOUNT_REQUEST: 'SETUP_BANK_ACCOUNT_REQUEST',
  SETUP_BANK_ACCOUNT_SUCCESS: 'SETUP_BANK_ACCOUNT_SUCCESS',
  SETUP_BANK_ACCOUNT_FAILURE: 'SETUP_BANK_ACCOUNT_FAILURE',
};

export { landingActionTypes as default };
