const myDealsActionTypes = {
  FETCH_MY_DEALS_REQUEST: 'FETCH_MY_DEALS_REQUEST',
  FETCH_MY_DEALS_SUCCESS: 'FETCH_MY_DEALS_SUCCESS',
  FETCH_MY_DEALS_FAILURE: 'FETCH_MY_DEALS_FAILURE',
};

export { myDealsActionTypes as default };
